# Generated by Django 5.2.7 on 2025-11-09 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_name', models.TextField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('password', models.TextField(max_length=128)),
            ],
            options={
                'verbose_name': 'Authority',
                'verbose_name_plural': 'Authorities',
                'db_table': 'authorities',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Hazard', 'Hazard type'), ('Infrastructure', 'Infrastructure Type')], max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['report_type'],
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Citizen',
                'verbose_name_plural': 'Citizens',
                'db_table': 'citizens',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], db_column='code', default='pending', max_length=15, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'db_table': 'status',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(choices=[('ROAD_DAMAGE', 'Road damage/Potholes'), ('STREETLIGHTS', 'Streetlights/Electrical Issues'), ('SIDEWALKS', 'Sidewalks/Pedestrian Paths'), ('BUILDING', 'Building/Structural Concerns'), ('BRIDGE', 'Bridge/Overpass Issues'), ('STRUCTURAL_COLLAPSE', 'Structural Collapses/Weak infrastructure'), ('SAFETY_SECURITY', 'Safety and Security Concerns'), ('INFRA_OTHER', 'Other (specify)'), ('FLOODING', 'Flooding/Water Overflow'), ('LANDSLIDE', 'Landslide/Soil Erosion'), ('FIRE_HAZARD', 'Fire Hazard'), ('ELECTRICAL_HAZARD', 'Electrical Hazard'), ('FALLEN_TREES', 'Fallen Trees/Debris Blocking Road'), ('ROAD_ACCIDENT', 'Road accident'), ('BLOCKED_DRAINAGE', 'Blocked Drainage/Clogged Gutter'), ('EARTHQUAKE', 'Earthquake Damage'), ('SINKHOLE', 'Sinkhole'), ('PUBLIC_HEALTH', 'Public Health Hazard'), ('HAZARD_OTHER', 'Other Hazard (specify)')], max_length=64)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'db_table': 'sub_categories',
                'ordering': ['report_type', 'sub_category'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, help_text='Title of report')),
                ('description', models.TextField(blank=True, help_text='Optional description of the issue', null=True)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude of the report location', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude of the report location', max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.citizen')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='api.status')),
                ('sub_category', models.ForeignKey(blank=True, help_text='Sub category of the report (required for Hazard category)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='api.subcategory')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
