# Generated by Django 5.2.7 on 2025-10-18 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Sub category of the report (required for Hazard category)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='api.subcategory'),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.TextField(blank=True, help_text='Title of report'),
        ),
    ]
