# Generated by Django 5.2.7 on 2026-01-10 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_categories_and_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='authority',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='api.authority'),
        ),
    ]
