# Generated by Django 5.2.7 on 2025-10-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seed_categories_and_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='Pending')),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'ordering': ['status'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='api.status'),
            preserve_default=False,
        ),
    ]
