# Generated by Django 5.2.7 on 2025-10-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_status_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='pending', max_length=15, unique=True),
        ),
    ]
