# Generated by Django 5.2.7 on 2025-10-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_status_status'),
    ]

    operations = [
    ]
