# Generated by Django 5.2.7 on 2025-10-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seed_statuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['code'], 'verbose_name_plural': 'Statuses'},
        ),
        migrations.RemoveField(
            model_name='status',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], db_column='code', default='pending', max_length=15, unique=True),
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
    ]
