version: "3.9"

services:
  django-web:
    build: .
    container_name: smartwayz-backend
    user: root
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
